ДЗ 1
MortemMK/2020-2-Atom-QA-Python-A-Kalinina pull request #1
Opened 2020-09-30 20:39 UTC by MortemMK

# Домашнее задание №1

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* подготовлено рабочее окружение для разработки автоматических тестов
* написаны тесты на типы данных в Python
*

2020-10-04 17:17 UTC, z1ll1 submitted a review, later dismissed
Это необязательно, но комментарии бы к тестам или названия тестов делать "говорящими". В целом норм.

2020-10-04 17:17 UTC, z1ll1 commented on homework-1/tests/test_dict.py
> +    assert list(d.values())[2] > list(d.values())[1]
No newline at end of file

2020-10-04 17:17 UTC, z1ll1 commented on homework-1/pytest.ini
> +[pytest]
А для чего тут pytest.ini? Не то чтобы это ошибка, может быть тут какие-то конфигурационные данные должны были быть?

2020-10-06 14:51 UTC, MortemMK commented on homework-1/pytest.ini
> +[pytest]
нет, данных не предусматривала. поправила ошибку, добавила комментарии к тестам и названия тоже постаралась изменить

2020-10-07 10:42 UTC, snicks92 commented
А зачем удалила pull_request_template.md?

2020-10-07 10:43 UTC, snicks92 requested changes
А зачем удалила pull_request_template.md?

2020-10-07 13:18 UTC, snicks92 approved these changes

2020-10-07 13:18 UTC, snicks92 commented
С моей стороны ОК

2020-10-09 10:04 UTC, merged

2020-10-09 10:04 UTC, snicks92 commented
Принято, спасибо